# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 03:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biomarketxapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroles',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userroles',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
