# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarketxapp', '0002_auto_20151217_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userroles',
            name='user',
        ),
        migrations.AddField(
            model_name='userroles',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
