# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarketxapp', '0003_auto_20151217_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
