# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarketxapp', '0006_users_how_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='name_org',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
