# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarketxapp', '0008_auto_20151219_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='projectimg/'),
        ),
    ]
