# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarketxapp', '0012_auto_20151221_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='user',
        ),
        migrations.AddField(
            model_name='lab',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
