# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarketxapp', '0021_auto_20160105_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Researcher_more_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('desc', models.TextField()),
                ('publications', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
