# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarketxapp', '0025_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('scientist_name', models.CharField(blank=True, max_length=250)),
                ('used_for', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Researcher_education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('institute', models.CharField(blank=True, max_length=250)),
                ('degree', models.CharField(blank=True, max_length=250)),
                ('field_study', models.CharField(blank=True, max_length=250)),
                ('study_start', models.CharField(blank=True, max_length=250)),
                ('study_stop', models.CharField(blank=True, max_length=250)),
                ('study_continue', models.CharField(blank=True, max_length=250)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Researcher_emplyment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('employer', models.CharField(blank=True, max_length=250)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('study_start', models.CharField(blank=True, max_length=250)),
                ('study_stop', models.CharField(blank=True, max_length=250)),
                ('study_continue', models.CharField(blank=True, max_length=250)),
                ('month_start', models.CharField(blank=True, max_length=250)),
                ('month_stop', models.CharField(blank=True, max_length=250)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Researcher_publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=500)),
                ('scientist_name', models.CharField(blank=True, max_length=250)),
                ('used_for', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ExampleModel',
        ),
        migrations.DeleteModel(
            name='image_details',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='researcher_more_info',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='researcher_more_info',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='lab',
            name='model_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='researcher_more_info',
            name='publications',
            field=models.CharField(max_length=250),
        ),
    ]
