# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biomarketxapp', '0028_auto_20160112_2006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LabProfilepic',
        ),
    ]
