# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarketxapp', '0031_auto_20160114_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='labservices',
            name='currency',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='labservices',
            name='unit',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
