# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarketxapp', '0040_auto_20160224_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='buyer_status',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='buyer_status'),
        ),
        migrations.AlterField(
            model_name='message',
            name='provider_status',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='provider_status'),
        ),
        migrations.AlterField(
            model_name='message',
            name='trash_status',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='trash_status'),
        ),
    ]
