# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biomarketxapp', '0041_auto_20160224_0541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='buyer_status',
            new_name='buyer_display_status',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='provider_status',
            new_name='provider_display_status',
        ),
    ]
