# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarketxapp', '0042_auto_20160224_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='buyer_display_status',
            field=models.IntegerField(null=True, verbose_name='buyer_display_status'),
        ),
        migrations.AlterField(
            model_name='message',
            name='provider_display_status',
            field=models.IntegerField(null=True, verbose_name='provider_display_status'),
        ),
        migrations.AlterField(
            model_name='message',
            name='trash_status',
            field=models.IntegerField(null=True, verbose_name='trash_status'),
        ),
    ]
