# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarketxapp', '0043_auto_20160224_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='trash_status',
        ),
        migrations.AddField(
            model_name='message',
            name='provider_sent_status',
            field=models.IntegerField(null=True, verbose_name='provider_sent_status'),
        ),
        migrations.AddField(
            model_name='quote_payments',
            name='charge_id',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='quote_payments',
            name='customer',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
