from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

	url(r'^$', views.index, name='index'),    
    url(r'^signup/$',views.signup_select, name='signup'),
    url(r'^signup/buyer/$',views.signup_researcher, name='signup_researcher'),
    url(r'^signup/provider/$',views.signup_lab, name='signup_lab'),
    url(r'^login/$',views.login, name='login'),
    url(r'^logout/$',views.logout_page, name='logout'),
    url(r'^about/$',views.about, name='about'),
    url(r'^consulting/$',views.new_consulting, name='new_consulting'),
    url(r'^support/$',views.new_contactus, name='support'),
    url(r'^services/(?P<ser_name>[A-Za-z0-9\w @%&._-]+)/$', views.show_services,name='show_services'),
    url(r'^services/sub/(?P<p_id>[A-Za-z0-9\w @%&._-]+)/$',views.new_services_inner, name='new_services_inner'),        
    url(r'^projects/$',views.new_projects, name='new_projects'),
    url(r'^edit-profile/$',views.editprofile, name='editprofile'),   
    url(r'^lab-services/$',views.lab_services, name='show_lab'),
    url(r'^lab-reviews/$',views.lab_reviews, name='lab_reviews'),
    url(r'^lab-endorse/$',views.lab_endorse, name='lab_endorse'),
    url(r'^show-your-lab/$',views.show_your_lab, name='show_your_lab'),    
    url(r'^list-your-lab/$',views.list_your_lab,name='list_your_lab'),
    url(r'^lab-profile-page/$',views.lab_profile_page,name='lab_profile_page'),    
    url(r'^edit-provider-profile/$',views.edit_lab_profile,name='edit_lab_profile'),
    # url(r'^edit-provider-services/(?P<lab_service_id>[A-Za-z0-9\w@%._-]+)/$',views.edit_lab_services,name='edit_lab_services'),
    url(r'^provider/lab-service/del/(?P<lab_service_id>[A-Za-z0-9\w@%._-]+)/$',views.del_lab_service,name='del_lab_service'),
    url(r'^provider/provider-service/edit/(?P<lab_service_id>[A-Za-z0-9\w@%._-]+)/$',views.edit_provider_service,name='edit_provider_service'),
    url(r'^lab-photos/$',views.upload_labphotos,name='upload_labphotos'),
    url(r'^upload-pic/$',views.upload_pic,name='upload_pic'),    
    url(r'^upload/profile-pic/$', views.upload_profile_pic,name='upload_profile_pic'),
    url(r'^login1/$',views.image_upload, name='login1'),
    url(r'^lab_list_all/$',views.lab_list_all, name='lab_list_all'),
    url(r'^autocomplete/$', views.searching_labs,name='autocomplete'),
    url(r'^search/$', views.search_result,name='search_result'),
    url(r'^search_keywords/$', views.search_keywords,name='search_keywords'),
    url(r'^searching/$', views.dynamic_searching,name='dynamic_searching'),
    url(r'^demo_publications/$', views. demo_publications,name=' demo_publications'),   
    url(r'^dashboard/$', views.dashboard,name='dashboard'),
    url(r'^search_filters/$', views.search_filters,name='search_filters'),
    url(r'^store-font/(?P<store_id>[0-9]+)/$', views.store_front,name='store_front'),    
    url(r'^parent-services$', views.add_parentservices,name='add_parentservices'),  
    url(r'^book$', views.book_detail,name='book_detail'),  
    url(r'^sample$', views.sample,name='sample'),
    
    url(r'^provider/$', views.labdashboard,name='labdashboard'),
    url(r'^provider/profile/$', views.new_lab_profile,name='new_lab_profile'),
    url(r'^provider/quotes/$', views.new_lab_quotes,name='new_lab_quotes'),
    url(r'^provider/messages/$', views.new_lab_messages,name='new_lab_messages'),
    url(r'^provider/desc/(?P<id>[0-9]+)$', views.view_quote,name='view_quote'),
    url(r'^provider-quote/(?P<qut_id>[0-9]+)/$', views.lab_send_quote,name='lab_send_quote'),
    url(r'^provider/orders/$', views.provider_orders,name='provider_orders'),
    url(r'^provider/order/(?P<ordr_id>[0-9]+)$', views.privider_order_desc,name='provider_order_desc'),
    
    url(r'^buyer/$',views.researcher_profile_page,name='researcher_profile_page'),    
    url(r'^buyer/quotes/$', views.new_res_quotes,name='new_res_quotes'),
    url(r'^buyer/desc/(?P<id>[0-9]+)$', views.res_view_quote,name='res_view_quote'),
    
    url(r'^buyer/edit/basics/$',views.edit_researcher_profile,name='edit_researcher_profile'),
    url(r'^buyer/edit/password/$',views.edit_researcher_password,name='edit_researcher_password'),
    url(r'^buyer/edit/education$',views.researcher_education,name='researcher_education'),
    url(r'^buyer/edit/education/add$',views.add_degree,name='add_degree'),
    url(r'^buyer/edit/education/edit/(?P<degree_id>[0-9]+)/$', views.edit_add_degree,name='edit_add_degree'),
    url(r'^buyer/edit/education/delete/(?P<degree_id>[0-9]+)/$', views.delete_degree,name='delete_degree'),
    url(r'^buyer/edit/publications/$', views.publications,name='add_publications'),
    url(r'^buyer/edit/publications/add$', views.add_publications,name='adding_pub'),
    url(r'^buyer/edit/publications/search$', views.search_publications,name='search_publications'),    
    url(r'^buyer/edit/publications/add/(?P<degree_id>[0-9]+)/$', views.store_publications,name='store_publications'),
    url(r'^buyer/edit/employment/$', views.researcher_employment,name='researcher_employment'),
    url(r'^buyer/edit/employment/add$', views.researcher_add_employment,name='researcher_add_employment'),
    url(r'^buyer/edit/employment/add/(?P<emp_id>[0-9]+)/$', views.edit_add_employment,name='edit_add_employment'),
    url(r'^buyer/edit/employment/delete/(?P<emp_id>[0-9]+)/$', views.delete_employment,name='delete_employment'),
    url(r'^buyer/edit/publications/delete/(?P<emp_id>[0-9]+)/$', views.delete_publications,name='delete_publications'),
    url(r'^buyer/orders/$', views.buyer_orders,name='buyer_orders'),
    url(r'^buyer/order/(?P<ordr_id>[0-9]+)$', views.buyer_order_desc,name='buyer_order_desc'),

    url(r'^send-quote/(?P<serv_id>[0-9]+)/(?P<lab_id>[0-9]+)/$', views.send_quote,name='send_quote'),   
    url(r'^multi-quote/(?P<serv_id>[0-9]+)/$', views.multiquote,name='multiquote'),
    url(r'^multiquote-res/(?P<serv_id>[0-9]+)/$', views.Multiquote_researcher,name='Multiquote_researcher'),    
    url(r'^quote-filter/$', views.quote_status_filter,name='quote_status_filter'),
    
    url(r'^send-quote/thanks/$', views.send_quote_thanks,name='send_quote_thanks'),
    url(r'^service-filters/$', views.service_filters,name='service_filters'),
    url(r'^breadcroomb/$', views.breadcroomb,name='breadcroomb'),

    url(r'^messages/$', views.allmessages, name='allmessages'),
    url(r'^buyer/messages/compose/$', views.compose, name='messages_compose'),
    url(r'^buyer/messages/inbox/$', views.inbox, name='messages_inbox'),
    url(r'^buyer/messages/sent/$', views.outbox, name='messages_outbox'),
    url(r'^buyer/messages/view/(?P<msg_id>[0-9]+)/$', views.buyer_msg_view, name='messages_view'),
    url(r'^buyer/messages/reply/(?P<msg_id>[0-9]+)/$', views.reply, name='messages_reply'),
    url(r'^buyer/messages/trash/$', views.trash, name='messages_trash'),
    url(r'^buyer/messages/trash-box/$', views.trash_messages, name='trash_messages'),
    url(r'^buyer/messages/trash-inbox/$', views.trash_move_inbox, name='trash_move_inbox'),
    url(r'^buyer/messages/trash-delete/$', views.trash_delete, name='trash_delete'),

    url(r'^compose/$', views.messages_compose, name='messages1_compose'),
    url(r'^provider-compose/$', views.provider_messages_compose, name='provider_messages_compose'),

    url(r'^provider/messages/compose/$', views.provider_compose, name='provider_messages_compose'),
    url(r'^provider/messages/inbox/$', views.provider_inbox, name='provider_messages_inbox'),
    url(r'^provider/messages/sent/$', views.provider_outbox, name='provider_messages_outbox'),
    url(r'^provider/messages/view/(?P<msg_id>[0-9]+)/$', views.provider_msg_view, name='provider_msg_view'),
    url(r'^provider/messages/reply/(?P<msg_id>[0-9]+)/$', views.provider_reply, name='provider_messages_reply'),
    url(r'^provider/messages/trash/$', views.provider_trash, name='provider_messages_trash'),
    url(r'^provider/messages/inbox-trash/$', views.move_inbox_trash_provider, name='move_inbox_trash_provider'),
    url(r'^provider/messages/trash-inbox/$', views.trash_move_inbox_provider, name='trash_move_inbox_provider'),
    url(r'^provider/messages/trash-delete/$', views.trash_delete_provider, name='trash_delete_provider'),
    url(r'^provider/messages/sent-trash/$', views.sent_box_provider, name='sent_box_provider'),

    
    url(r'^sort-by-value/$', views.sort_by_value,name='sort_by_value'),    
    url(r'^quote-accept/(?P<qut_id>[0-9]+)/$', views.Quote_accept,name='Quote_accept'),
     url(r'^buyer/quote-reject/(?P<qut_id>[0-9]+)/$', views.Quote_reject,name='Quote_reject'),
    url(r'^testing/$', views.testing, name='testing'),
    url(r'^lab-search-filters/$', views.lab_serch_filters, name='lab_serch_filters'),
    url(r'^proceed-payment/$', views.quote_payment_form, name='quote_payment_form'),
    url(r'^buyer/quote-accept/creditcard/(?P<qut_id>[0-9]+)/$', views.buyer_quote_accept_creditcard, name='buyer_quote_accept_creditcard'),
    url(r'^buyer/payment-type/(?P<qut_id>[0-9]+)/$', views.select_payment_type, name='select_payment_type'),
    url(r'^buyer/quote-accept/wiretransfer/(?P<qut_id>[0-9]+)/$', views.wiretransfer_payment, name='wiretransfer_payment'),
    url(r'^buyer/workroom/(?P<ordr_id>[0-9]+)/$', views.workroom_allocation,name='workroom_allocation'),    
    url(r'^provider/workroom/(?P<ordr_id>[0-9]+)/$', views.provider_workroom,name='provider_workroom'),    


    url(r'^edit/$', views.admin_edit_static, name='admin_edit_static'),
    url(r'^edit1/$', views.admin_edit_staticdata_display,name='admin_edit_staticdata_display'),
    url(r'^staticpage/$', views.admin_staticdata, name='admin_staticdata'),
    url(r'^about_static/$', views.about_static, name='about_static'),

    url(r'^edit_consult/$', views.consulting_edit, name='consulting_edit'),
    url(r'^consult_static/$', views.consulting_static, name='consulting_static'),

    url(r'^projects_edit/$', views.projects_edit, name='projects_edit'),
    url(r'^projects_static/$', views.projects_static, name='projects_static'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)