# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarketxapp', '0007_users_name_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='caption',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='lab',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
