# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarketxapp', '0010_lab_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='labservices',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
