# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarketxapp', '0013_auto_20151221_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labservices',
            name='service_id',
        ),
        migrations.AlterField(
            model_name='labservices',
            name='lab_id',
            field=models.IntegerField(),
        ),
    ]
