# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biomarketxapp', '0015_auto_20151221_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labendorse',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='labreviews',
            name='service_id',
        ),
    ]
