# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biomarketxapp', '0019_auto_20160105_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
