# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarketxapp', '0029_delete_labprofilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labkeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_keywords', models.TextField(max_length=250)),
            ],
        ),
    ]
