# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarketxapp', '0030_labkeywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='model_pic',
            field=models.ImageField(blank=True, null=True, upload_to='pic_folder/'),
        ),
    ]
