# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarketxapp', '0038_quote_status_quote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote_files',
            name='sent_by',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='quotes',
            name='sent_by',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
