# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biomarketxapp', '0046_auto_20160229_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='trash_status',
        ),
    ]
