# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarketxapp', '0048_auto_20160301_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_status',
            name='order_id',
            field=models.IntegerField(null=True),
        ),
    ]
