# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarketxapp', '0049_order_status_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_files',
            name='sender_id',
        ),
        migrations.AddField(
            model_name='order_files',
            name='sent_by',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='filename',
            field=models.FileField(upload_to='quotes'),
        ),
    ]
