# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 11:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('biomarketxapp', '0051_workroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='workroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 2, 11, 8, 18, 119526, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workroom',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='workroom',
            name='order_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='workroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 2, 11, 8, 28, 645190, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
