# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarketxapp', '0052_auto_20160302_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='workroom',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='workroom',
            name='user_role',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
