# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarketxapp', '0053_auto_20160303_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='workroom_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(null=True)),
                ('filename', models.FileField(upload_to='quotes')),
            ],
        ),
    ]
