# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarketxapp', '0056_workroom_files_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='edit_about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
            ],
        ),
    ]
